const CATEGORIES = [
  { id: "pro-tools", name: "Pro Tools", icon: "🎚", color: "#7C3AED" },
  { id: "ir-209", name: "IR-209", icon: "🎓", color: "#059669" },
  { id: "sound-synthesis", name: "Sound & Synthesis", icon: "🎛️", color: "#DB2777" },
];

const QUIZZES = [
  {
    id: "pt-shortcuts-1",
    category: "pro-tools",
    title: "Pro Tools Keyboard Shortcuts",
    description: "Test your knowledge of essential Pro Tools keyboard shortcuts for Mac.",
    timePerQuestion: 0,
    questions: [
      { q: "What is the shortcut to create an automation breakpoint?", options: ["Command + Click (in Automation Lane)", "Option + Click", "Control + Command + Click", "Command + Shift + Click"], answer: 0 },
      { q: "What is the shortcut to delete an automation breakpoint?", options: ["Command + Click", "Option + Click", "Control + Click", "Shift + Click"], answer: 1 },
      { q: "What shortcut enables plugin parameter automation?", options: ["Control + Command + Click", "Control + Command + Option + Click", "Option + Shift + Click", "Command + Shift + Click"], answer: 1 },
      { q: "How do you use fine resolution while dragging in Pro Tools?", options: ["Hold Option while dragging", "Hold Shift while dragging", "Hold Command while dragging", "Hold Control while dragging"], answer: 2 },
      { q: "What shortcut displays plugin parameter automation?", options: ["Control + Command + Click", "Option + Command + Click", "Control + Option + Click", "Shift + Command + Click"], answer: 0 },
      { q: "What shortcut shows the Volume Automation Lane on all tracks?", options: ["Option + =", "Option + -", "Command + -", "Control + -"], answer: 1 },
      { q: "What shortcut shows the Volume Automation Lane on the selected track?", options: ["-", "+", "=", "Option + ="], answer: 2 },
      { q: "What shortcut thins selected automation?", options: ["Option + Command + T", "Command + Shift + T", "Control + Option + T", "Option + Shift + T"], answer: 0 },
      { q: "What shortcut clears unused clips?", options: ["Command + Shift + U", "Command + Shift + B", "Option + Shift + B", "Command + Option + B"], answer: 1 },
      { q: "What shortcut selects unused clips?", options: ["Command + Shift + B", "Command + Shift + U", "Option + Shift + U", "Command + Option + U"], answer: 1 },
      { q: "What shortcut shows/hides Audio Clips in the Clips List?", options: ["Command + Shift + 2 on Numpad", "Command + Shift + 1 on Numpad", "Option + Shift + 1", "Control + Shift + 1"], answer: 1 },
      { q: "What shortcut shows/hides MIDI Clips in the Clips List?", options: ["Command + Shift + 1 on Numpad", "Command + Shift + 2 on Numpad", "Option + Shift + 2", "Control + Shift + 2"], answer: 1 },
      { q: "What shortcut creates a new session?", options: ["Command + Shift + N", "Command + N", "Command + Shift + O", "Control + N"], answer: 1 },
      { q: "What shortcut opens a recent session?", options: ["Command + O", "Command + Shift + N", "Command + Shift + O", "Option + O"], answer: 2 },
      { q: "What shortcut bounces the mix?", options: ["Command + B", "Option + Command + B", "Option + Shift + B", "Control + B"], answer: 1 },
      { q: "What shortcut bypasses all plugins on selected tracks?", options: ["Shift + Q", "Shift + A", "Shift + B", "Command + Shift + A"], answer: 1 },
      { q: "What shortcut bypasses all sends on selected tracks?", options: ["Shift + A", "Shift + S", "Shift + Q", "Command + Shift + Q"], answer: 2 },
      { q: "What shortcut closes all floating windows?", options: ["Control + Option + Command + W", "Command + Shift + W", "Option + Command + W", "Control + Command + W"], answer: 0 },
      { q: "What shortcut closes the current session?", options: ["Command + W", "Command + Shift + W", "Control + W", "Option + W"], answer: 1 },
      { q: "What shortcut consolidates clips?", options: ["Option + Shift + 2", "Option + Shift + 3", "Command + Shift + 3", "Control + Shift + 3"], answer: 1 },
      { q: "What shortcut creates fades?", options: ["Command + Shift + F", "Option + F", "Command + F", "Control + F"], answer: 2 },
      { q: "What shortcut duplicates a clip?", options: ["Command + C", "Command + V", "Command + D", "Command + Shift + D"], answer: 2 },
      { q: "What shortcut extends the selection to the beginning?", options: ["Shift + Option + Return", "Shift + Return", "Command + Return", "Option + Return"], answer: 1 },
      { q: "What shortcut extends the selection to the end?", options: ["Shift + Return", "Shift + Option + Return", "Command + Option + Return", "Control + Return"], answer: 1 },
      { q: "What shortcut fades in from start to cursor?", options: ["F", "G", "D", "A"], answer: 2 },
      { q: "What shortcut fades out from cursor to end?", options: ["D", "F", "A", "G"], answer: 3 },
      { q: "What shortcut executes fades using last settings?", options: ["D", "G", "F", "A"], answer: 2 },
      { q: "What shortcut groups clips?", options: ["Option + Command + U", "Option + Command + G", "Command + Shift + G", "Control + G"], answer: 1 },
      { q: "What shortcut imports audio?", options: ["Command + Shift + I", "Command + I", "Option + Shift + I", "Control + I"], answer: 0 },
      { q: "What shortcut imports session data?", options: ["Command + Shift + I", "Option + Shift + I", "Control + Shift + I", "Command + Option + I"], answer: 1 },
      { q: "What shortcut mutes a clip?", options: ["Command + Shift + M", "Option + M", "Command + M", "Control + M"], answer: 2 },
      { q: "What shortcut separates a clip at the selection?", options: ["S", "A", "B", "D"], answer: 2 },
      { q: "What shortcut snaps the clip start to the insertion point?", options: ["Control + Command + Click", "Control + Click", "Option + Click", "Command + Click"], answer: 1 },
      { q: "What shortcut snaps the clip end to the insertion point?", options: ["Control + Click", "Option + Command + Click", "Control + Command + Click", "Shift + Click"], answer: 2 },
      { q: "What shortcut suspends or un-suspends groups?", options: ["Command + Shift + U", "Command + Shift + G", "Option + G", "Control + G"], answer: 1 },
      { q: "What shortcut switches between the Edit and Mixer window?", options: ["Command + Shift + Equal", "Command + Equal", "Option + Equal", "Control + Equal"], answer: 1 },
      { q: "What shortcut trims the clip end to the cursor?", options: ["A", "T", "S", "D"], answer: 2 },
      { q: "What shortcut trims the clip start to the cursor?", options: ["S", "A", "D", "B"], answer: 1 },
      { q: "What shortcut trims a clip to the selection?", options: ["Command + Shift + T", "Option + T", "Command + T", "Control + T"], answer: 2 },
      { q: "What shortcut turns on the Smart Tool?", options: ["Command + 5", "Command + 6", "Command + 7", "Command + 8"], answer: 2 },
      { q: "What shortcut turns on/off Tab to Transient?", options: ["Command + Tab", "Option + Tab", "Command + Option + Tab", "Control + Tab"], answer: 2 },
      { q: "What shortcut turns on Keyboard Focus?", options: ["Option + Command + 2", "Option + Command + 1", "Command + Shift + 1", "Control + Option + 1"], answer: 1 },
      { q: "What shortcut ungroups clips?", options: ["Option + Command + G", "Option + Command + U", "Command + Shift + U", "Control + U"], answer: 1 },
      { q: "What shortcut turns on/off the click track?", options: ["7 on Numpad", "8 on Numpad", "9 on Numpad", "6 on Numpad"], answer: 1 },
      { q: "What shortcut turns on/off the metronome?", options: ["8 on Numpad", "7 on Numpad", "6 on Numpad", "9 on Numpad"], answer: 1 },
      { q: "What shortcut turns on/off the count off?", options: ["8 on Numpad", "6 on Numpad", "7 on Numpad", "9 on Numpad"], answer: 2 },
      { q: "What shortcut nudges a clip by the selected amount?", options: ["Left or Right Arrow", "Plus or Minus on Numpad", "Command + Left or Right Arrow", "Option + Left or Right Arrow"], answer: 1 },
      { q: "What shortcut opens the Keyboard Commands window?", options: ["Control + Shift + W", "Control + Shift + K", "Command + Shift + K", "Option + Shift + K"], answer: 1 },
      { q: "What shortcut clears clip indicators?", options: ["Option + I", "Command + C", "Option + C", "Control + C"], answer: 2 },
      { q: "What shortcut turns on/off Link Track and Edit Selection?", options: ["Command + T", "Option + T", "Shift + T", "Control + T"], answer: 2 },
      { q: "What shortcut turns all MIDI notes off?", options: ["Shift + Command + .", "Command + Option + .", "Control + Shift + .", "Option + Shift + ."], answer: 0 },
      { q: "What shortcut opens the MIDI Editor?", options: ["Control + Option + Equal", "Control + Equal", "Command + Equal", "Option + Equal"], answer: 1 },
      { q: "What shortcut opens the MIDI Typing Keyboard?", options: ["Control + K", "Command + K", "Shift + K", "Option + K"], answer: 2 },
      { q: "What shortcut increases or decreases MIDI velocity by 5?", options: ["Shift + Up or Down Arrow", "Command + Shift + Up or Down Arrow", "Command + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 2 },
      { q: "What shortcut increases or decreases MIDI velocity by 15?", options: ["Command + Up or Down Arrow", "Command + Shift + Up or Down Arrow", "Shift + Up or Down Arrow", "Option + Shift + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut transposes MIDI up or down an octave?", options: ["Command + Up or Down Arrow", "Option + Up or Down Arrow", "Shift + Up or Down Arrow", "Control + Up or Down Arrow"], answer: 2 },
      { q: "What shortcut shows/hides the MIDI Event List?", options: ["Option + Equal", "Control + Equal", "Command + Equal", "Shift + Equal"], answer: 0 },
      { q: "What shortcut trims MIDI end by grid value?", options: ["Control + Left or Right Arrow", "Option + Left or Right Arrow", "Command + Left or Right Arrow", "Shift + Left or Right Arrow"], answer: 1 },
      { q: "What shortcut trims MIDI start by grid value?", options: ["Option + Left or Right Arrow", "Command + Left or Right Arrow", "Control + Left or Right Arrow", "Shift + Left or Right Arrow"], answer: 2 },
      { q: "What shortcut creates a new track?", options: ["Command + N", "Command + T", "Command + Shift + N", "Control + Shift + N"], answer: 2 },
      { q: "What shortcut changes from mono to stereo in the New Track window?", options: ["Command + Up or Down Arrow", "Command + Shift + Left or Right Arrow", "Command + Left or Right Arrow", "Option + Left or Right Arrow"], answer: 2 },
      { q: "What shortcut changes the track type in the New Track window?", options: ["Command + Left or Right Arrow", "Command + Up or Down Arrow", "Shift + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut zooms in and out horizontally in Pro Tools?", options: ["Command + [ or ]", "Option + [ or ]", "R and T", "Z and X"], answer: 2 },
      { q: "What shortcut changes all track heights in the session?", options: ["Control + Up or Down Arrow", "Control + Option + Up or Down Arrow", "Command + Option + Up or Down Arrow", "Shift + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut changes the selected track height?", options: ["Control + Option + Up or Down Arrow", "Control + Up or Down Arrow", "Command + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut zooms in on a selection horizontally?", options: ["Control + Command + [", "Control + Command + ]", "Option + Command + ]", "Command + Shift + ]"], answer: 1 },
      { q: "What shortcut zooms to show all horizontally and preserves waveform zoom?", options: ["Option + A", "Control + Command + ]", "Control + Command + [", "Command + Shift + ["], answer: 2 },
      { q: "What shortcut zooms to show all horizontally and resets waveform zoom?", options: ["Control + Command + [", "Control + Command + ]", "Option + A", "Command + Option + A"], answer: 2 },
      { q: "What shortcut zooms in and out audio waveforms?", options: ["R and T", "Command + [ or ]", "Command + Option + [ or ]", "Control + [ or ]"], answer: 2 },
      { q: "What shortcut fits all track sizes to the window?", options: ["Control + Option + Up or Down Arrow", "Control + Option + Command + Down Arrow", "Control + Command + Down Arrow", "Option + Command + Down Arrow"], answer: 1 },
      { q: "What shortcut cycles through playlists on selected tracks?", options: ["Command + Up or Down Arrow", "Control + Up or Down Arrow", "Shift + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 2 },
      { q: "What shortcut cycles through playlists within a selection?", options: ["Shift + Up or Down Arrow", "Shift + Command + Up or Down Arrow", "Control + Shift + Up or Down Arrow", "Option + Shift + Up or Down Arrow"], answer: 1 },
    ]
  }
  ,{
    id: "ir209-final-review",
    category: "ir-209",
    title: "IR-209 Final Review",
    description: "Comprehensive review of all 12 lessons — Pro Tools, digital audio, microphones, electricity, hearing protection, and more.",
    timePerQuestion: 0,
    questions: [
      { q: "At any single instant in time, how many instructions does a speaker cone receive?", options: ["One", "One per track", "One per frequency", "As many as there are tracks"], answer: 0 },
      { q: "Why can't you hear sound from a single isolated sample?", options: ["The sample rate is too low", "There isn't enough time for motion to occur", "The bit depth is too shallow", "The speaker hasn't been initialized"], answer: 1 },
      { q: "What happens to multiple sounds at the same instant in time?", options: ["They are stacked on top of each other", "They are stored separately in the speaker", "They are summed into one single motion", "They cancel each other out"], answer: 2 },
      { q: "What is the purpose of having separate tracks in a DAW?", options: ["So each track can use a different sample rate", "So we can control how much influence each sound has before they're combined", "So the computer processes them simultaneously", "So the speaker can move in multiple directions"], answer: 1 },
      { q: "When you zoom extremely far into a waveform and play a tiny slice, what do you hear?", options: ["The full song at a very high pitch", "Nothing — or a faint click", "A clean sine wave", "The loudest moment of the track"], answer: 1 },
      { q: "Sound exists as:", options: ["A position in space", "Motion across time", "A static air pressure value", "A voltage at a single moment"], answer: 1 },
      { q: "What is mixing, at its most fundamental level?", options: ["Adding reverb and compression to tracks", "Converting analog signals to digital", "Shaping motion — controlling how much influence each sound has before combining", "Editing clips on a timeline"], answer: 2 },
      { q: "When you duplicate a track and play both together, the waveform gets taller. What does this represent?", options: ["A new sound has been added", "More movement — this is summing", "The track has been doubled in bit depth", "The sample rate has increased"], answer: 1 },
      { q: "What is the role of iLok in a Pro Tools setup?", options: ["It installs Pro Tools updates", "It manages which version of Pro Tools is downloaded", "It authorizes Pro Tools to run by verifying a valid license", "It controls the audio interface drivers"], answer: 2 },
      { q: "What does Avid Link do?", options: ["Stores and verifies Pro Tools licenses", "Downloads, installs, and updates Pro Tools and Avid plugins", "Converts sessions between sample rates", "Manages iLok cloud sessions"], answer: 1 },
      { q: "Which of the following correctly describes iLok Cloud licensing?", options: ["It stores the license on a USB key", "It requires an internet connection and an active cloud session", "It is built into the Mac operating system", "It only works on Apple Silicon machines"], answer: 1 },
      { q: "What is the key difference between installing Pro Tools and authorizing Pro Tools?", options: ["They are the same process", "Installing places the app on your computer; authorization determines if it's allowed to run", "Authorization is handled by Avid Link; installing is handled by iLok", "Installing requires internet; authorization is offline only"], answer: 1 },
      { q: "What does 'No license found' typically indicate in Pro Tools?", options: ["Pro Tools needs to be reinstalled", "There is a licensing problem, not an installation problem", "The audio interface is disconnected", "The session file is corrupted"], answer: 1 },
      { q: "In Apple Silicon Macs, CPU, GPU, and memory share the same chip. This is called:", options: ["Hyperthread memory", "Unified memory", "Shared core architecture", "Dynamic RAM pooling"], answer: 1 },
      { q: "What is the recommended minimum free disk space to maintain on your internal drive?", options: ["5-10%", "10-15%", "20-25%", "30-40%"], answer: 2 },
      { q: "For active Pro Tools sessions, which external drive type is strongly recommended?", options: ["External HDD via USB 2.0", "External SSD via USB 3.0 or Thunderbolt", "External HDD via Thunderbolt", "Cloud storage via iCloud Drive"], answer: 1 },
      { q: "Why should you avoid updating macOS immediately when a new version is released?", options: ["New macOS versions always remove Pro Tools from the system", "Audio drivers and plugins often lag months behind Apple OS updates", "iLok licenses expire when macOS updates", "Pro Tools requires manual reinstallation after every update"], answer: 1 },
      { q: "What does the Pro Tools System Usage window show?", options: ["Session tempo and key signature", "CPU usage, disk activity, and memory pressure", "Plugin latency values", "Bit depth and sample rate of the session"], answer: 1 },
      { q: "What causes a CPU overload error in Pro Tools?", options: ["The hard drive is too slow", "Too many heavy plugins running in real time exceed what the CPU can process before the next audio moment", "The session sample rate does not match the interface", "There is a licensing issue with iLok"], answer: 1 },
      { q: "iZotope plugins are managed through:", options: ["iLok License Manager", "Avid Link", "iZotope Product Portal", "Pro Tools Plugin Manager"], answer: 2 },
      { q: "Which drive format is required for modern macOS systems?", options: ["FAT32", "ExFAT", "Mac OS Extended (HFS+)", "APFS"], answer: 3 },
      { q: "What keyboard shortcut opens the Force Quit window on a Mac?", options: ["Command + Q", "Command + Option + Esc", "Command + Shift + Esc", "Control + Option + Delete"], answer: 1 },
      { q: "What application shows real-time CPU, memory, and disk usage on a Mac?", options: ["System Information", "Terminal", "Activity Monitor", "Console"], answer: 2 },
      { q: "What does Command + I do in Finder?", options: ["Imports a file into the DAW", "Opens Get Info for the selected item", "Starts a Finder search", "Opens iCloud settings"], answer: 1 },
      { q: "What does the Spacebar do in Finder?", options: ["Renames the selected file", "Quick Look preview of the selected file", "Moves the file to Trash", "Duplicates the file"], answer: 1 },
      { q: "Why is it important to eject an external drive before unplugging it?", options: ["To prevent the drive from overheating", "External drives cache data; unplugging without ejecting risks corruption", "So Pro Tools can save the session properly", "Because macOS will delete unsaved audio if the drive is removed suddenly"], answer: 1 },
      { q: "What shortcut opens Go to Folder in Finder?", options: ["Command + F", "Command + Shift + G", "Command + Option + F", "Command + G"], answer: 1 },
      { q: "What is the difference between Command + W and Command + Q in macOS?", options: ["Command + W quits the app; Command + Q closes the window", "Command + W closes the window; Command + Q quits the app", "They both close the current window", "They both quit the application"], answer: 1 },
      { q: "AAX plugins for Pro Tools are located at:", options: ["/Library/Audio/Plug-Ins/Components", "/Library/Audio/Plug-Ins/VST3", "/Library/Application Support/Avid/Audio/Plug-Ins", "/Applications/Avid/Plugins"], answer: 2 },
      { q: "Why is iCloud Drive NOT a suitable location for active Pro Tools sessions?", options: ["iCloud Drive does not support audio file formats", "iCloud can remove local copies of files, interrupt access, and silently change file paths", "Pro Tools cannot open files stored in iCloud", "iCloud has a 2GB file size limit"], answer: 1 },
      { q: "What is the difference between sync and backup?", options: ["Sync creates multiple versions; backup deletes old versions", "Sync mirrors changes everywhere including deletions; backup preserves a separate copy", "They are the same thing", "Backup requires an internet connection; sync is local only"], answer: 1 },
      { q: "What does the Optimize Mac Storage iCloud setting do?", options: ["Compresses audio files to save space", "May remove local copies of files to free up space, leaving only cloud versions", "Deletes duplicate files automatically", "Converts audio to a smaller format"], answer: 1 },
      { q: "Which iCloud setting is considered most dangerous for audio engineers to enable?", options: ["Photos sync", "iCloud Keychain", "Desktop and Documents Folder syncing", "Mail sync"], answer: 2 },
      { q: "What does EIN measure in an audio interface?", options: ["The maximum input level before clipping", "The dynamic range of the converters", "How much noise the microphone preamp generates internally", "The headphone output power"], answer: 2 },
      { q: "What is headroom in the context of an audio interface?", options: ["The difference between 0 dBFS and the standard operating level", "The maximum number of tracks the interface can record simultaneously", "The safety margin between standard operating level and the point where distortion begins", "The amount of gain the preamp can apply"], answer: 2 },
      { q: "What happens if you plug a passive guitar directly into a low-impedance mic input?", options: ["The signal is boosted too high and clips", "The pickup becomes loaded — high frequencies are lost and tone becomes dull", "The interface automatically switches to instrument mode", "Nothing — modern interfaces handle any input type"], answer: 1 },
      { q: "What does MADI stand for?", options: ["Multi-Audio Digital Integration", "Multichannel Audio Digital Interface", "Master Audio Distribution Interface", "Multi-Addressable Digital Input"], answer: 1 },
      { q: "How many channels can MADI typically carry at 48 kHz?", options: ["Up to 8", "Up to 16", "Up to 32", "Up to 64"], answer: 3 },
      { q: "What is Dante?", options: ["A Pro Tools plugin for routing", "A type of microphone preamp", "The most widely adopted Audio over IP system in professional audio", "A digital audio format similar to ADAT"], answer: 2 },
      { q: "ADAT Lightpipe typically carries how many channels at 48 kHz?", options: ["2 channels", "4 channels", "8 channels", "16 channels"], answer: 2 },
      { q: "What is the purpose of Word Clock in a digital audio system?", options: ["To sync MIDI data between instruments", "To ensure all digital devices convert audio at exactly the same time", "To control the sample rate of individual tracks", "To regulate the power supply voltage"], answer: 1 },
      { q: "What is jitter in digital audio?", options: ["A type of digital noise caused by low bit depth", "Tiny random variations in the timing of sampling pulses", "Distortion caused by aliasing above the Nyquist frequency", "Low-frequency rumble from a mechanical hard drive"], answer: 1 },
      { q: "What is the key difference between MADI and AoIP like Dante?", options: ["MADI uses Ethernet; Dante uses coaxial cable", "MADI is a direct point-to-point pipe; Dante is a shared network system", "Dante only works with Avid hardware; MADI is universal", "MADI requires a dedicated clock; Dante does not"], answer: 1 },
      { q: "THD+N measures:", options: ["Total headroom and dynamic range", "How much harmonic distortion and noise is added by the interface circuitry", "The transient response of the preamp", "Total harmonic depth and noise floor"], answer: 1 },
      { q: "What physical principle do both dynamic microphones and loudspeakers rely on?", options: ["Capacitance", "Electrostatic attraction", "Electromagnetic induction", "Piezoelectric effect"], answer: 2 },
      { q: "Why do moving-coil microphones exhibit a natural high-frequency roll-off?", options: ["They use a small capacitor that blocks high frequencies", "The diaphragm and coil have physical mass, causing slower response", "The ribbon is too thin to capture high frequencies", "They require phantom power to capture high frequencies"], answer: 1 },
      { q: "Condenser microphones require phantom power for which two reasons?", options: ["To power the LED indicator and charge the battery", "To polarize the capsule and power the internal amplifier", "To heat the tube and stabilize the preamp", "To activate the pad switch and power the high-pass filter"], answer: 1 },
      { q: "What is the proper procedure when applying phantom power?", options: ["Plug in the mic while phantom power is on then unmute", "Turn down monitors, mute the channel, lower gain, engage phantom power, wait, then bring gain back up", "Engage phantom power first then connect the microphone", "Connect the mic, hit record, then engage phantom power"], answer: 1 },
      { q: "What type of microphone has the strongest proximity effect?", options: ["Omnidirectional", "Cardioid", "Figure-8", "Hypercardioid"], answer: 2 },
      { q: "The proximity effect in directional microphones is best described as:", options: ["A boost in high frequencies when the source is close", "Reduced low-frequency cancellation when the source moves close, resulting in apparent bass boost", "A reduction in sensitivity when the source is too close", "An increase in noise floor at close distances"], answer: 1 },
      { q: "Why are tube microphones often suspended upside down?", options: ["To prevent wind noise from entering the capsule", "To reduce handling noise from the stand", "So rising heat from the tube moves away from the capsule", "Because the output XLR is at the top"], answer: 2 },
      { q: "What does a DI box do?", options: ["Converts digital signals to analog for outboard gear", "Matches impedance, converts instrument level to mic level, and balances the signal", "Splits a stereo signal into two mono signals", "Amplifies a condenser mic signal to line level"], answer: 1 },
      { q: "Sensitivity in microphones tells you:", options: ["How fast the diaphragm responds to transients", "How directional the microphone is", "How much electrical output voltage the microphone produces for a given acoustic input", "How much gain the microphone needs from the preamp"], answer: 2 },
      { q: "Which microphone type typically has the fastest transient response?", options: ["Moving-coil dynamic", "Ribbon dynamic", "Large-diaphragm condenser", "Small-diaphragm condenser"], answer: 3 },
      { q: "An omnidirectional microphone does NOT exhibit proximity effect because:", options: ["It uses a ribbon element", "It requires phantom power", "It is a pure pressure microphone with no rear signal path and therefore no phase cancellation mechanism", "Its diaphragm is too large to respond to proximity changes"], answer: 2 },
      { q: "What is the ground lift switch on a DI box used for?", options: ["To boost the low-frequency response", "To switch between active and passive modes", "To break a ground loop that can cause hum", "To engage the instrument pad"], answer: 2 },
      { q: "What is the standard operating level (SOL) for professional analog audio equipment?", options: ["+4 dBV", "-10 dBu", "+4 dBu", "0 dBFS"], answer: 2 },
      { q: "A VU meter has a mechanical needle with a rise time of approximately:", options: ["10 ms", "300 ms", "1 second", "50 ms"], answer: 1 },
      { q: "What does RMS metering show?", options: ["The absolute peak level of the signal", "The average energy of the signal over a short time window", "The digital full scale ceiling", "The headroom before clipping"], answer: 1 },
      { q: "What does dBFS stand for?", options: ["Decibels Full Scale", "Decibels Frequency Scale", "Decibels Fixed Standard", "Decibels Frequency Spectrum"], answer: 0 },
      { q: "At Berklee, the standard operating level is calibrated at:", options: ["-20 dBFS", "-18 dBFS", "-16 dBFS", "-12 dBFS"], answer: 2 },
      { q: "What is True Peak metering designed to detect?", options: ["Clipping inside plugins", "Inter-sample peaks — levels the signal may reach after digital-to-analog conversion", "The RMS level of the master bus", "Gain reduction from compression"], answer: 1 },
      { q: "What does LUFS measure?", options: ["Peak loudness at any given moment", "The average loudness of audio over time matching human perception", "The dynamic range of the master bus", "The bit depth of the output file"], answer: 1 },
      { q: "Why should a reference mix be routed to a pre-master fader track?", options: ["So it can be exported with the final mix", "So it receives the same processing as the mix", "To avoid adding any master bus processing to the reference track", "So it can be compared at a higher volume"], answer: 2 },
      { q: "When streaming platforms normalize audio to -14 LUFS, what do they actually change?", options: ["The dynamic range and compression of the track", "Only the playback volume — not the mix or dynamics", "The sample rate and bit depth", "The frequency balance of the track"], answer: 1 },
      { q: "Voltage in an electrical circuit is defined as:", options: ["The flow of electrical charge through a circuit", "The opposition to current flow", "The difference in electrical potential between points in a circuit", "The rate of energy consumption"], answer: 2 },
      { q: "According to Ohm's Law, if resistance decreases while voltage stays the same, what happens to current?", options: ["Current decreases", "Current stays the same", "Current increases", "Current becomes zero"], answer: 2 },
      { q: "What is the formula for electrical power?", options: ["P = V / I", "P = V x R", "P = V x I", "P = I / R"], answer: 2 },
      { q: "Why do we use impedance instead of resistance in audio circuits?", options: ["Because audio signals are too weak for standard resistance measurements", "Because audio uses AC signals and impedance accounts for frequency-dependent changes that resistance does not", "Because impedance is measured in watts which is more useful for audio", "Because resistance only applies to digital signals"], answer: 1 },
      { q: "In professional audio, input impedance should be approximately how much higher than output impedance?", options: ["Twice as high", "Five times as high", "Ten times as high", "Equal to each other"], answer: 2 },
      { q: "A decibel fundamentally measures:", options: ["An absolute level of loudness", "A change or comparison between two levels", "The frequency content of a signal", "The amplitude at a single instant"], answer: 1 },
      { q: "The decibel formula for power is:", options: ["dB = 20 x log(P1 / P0)", "dB = 10 x log(P1 / P0)", "dB = 10 x log(V1 / V0)", "dB = 20 x log(P1 x P0)"], answer: 1 },
      { q: "Doubling the power of a signal results in a change of approximately:", options: ["+6 dB", "+10 dB", "+3 dB", "+1 dB"], answer: 2 },
      { q: "Doubling the voltage of a signal results in a change of approximately:", options: ["+3 dB", "+6 dB", "+10 dB", "+20 dB"], answer: 1 },
      { q: "To sound approximately twice as loud, you need roughly how many times the power?", options: ["2x", "4x", "10x", "100x"], answer: 2 },
      { q: "The decibel formula for voltage is:", options: ["dB = 10 x log(V1 / V0)", "dB = 20 x log(P1 / P0)", "dB = 20 x log(V1 / V0)", "dB = 10 x log(V1 x V0)"], answer: 2 },
      { q: "What does a -20 dB change in power represent?", options: ["1/2 the power", "1/10 the power", "1/100 the power", "1/1000 the power"], answer: 2 },
      { q: "At what dB level does sound begin to pose a risk of hearing damage over time?", options: ["70 dB", "75 dB", "85 dB", "95 dB"], answer: 2 },
      { q: "If safe exposure at 85 dB is 8 hours, what is the safe exposure at 88 dB?", options: ["6 hours", "4 hours", "2 hours", "1 hour"], answer: 1 },
      { q: "Every 3 dB increase in level cuts safe exposure time in half. Why?", options: ["Because 3 dB represents double the power", "Because 3 dB is the threshold of human hearing", "Because 3 dB equals one stop of dynamic range", "Because the ear's acoustic reflex takes 3 dB to trigger"], answer: 0 },
      { q: "What is tinnitus?", options: ["Temporary hearing loss after loud exposure", "A permanent ringing buzzing or hissing sound caused by auditory system damage", "Sensitivity to low-frequency sounds only", "A condition where bass frequencies cause pain"], answer: 1 },
      { q: "What is hyperacusis?", options: ["The ability to hear extremely high frequencies", "A condition where the auditory system becomes hypersensitive and normal sounds become painfully loud", "Temporary threshold shift after a concert", "Excessive low-frequency sensitivity"], answer: 1 },
      { q: "The acoustic reflex takes approximately how long to engage?", options: ["1 millisecond", "10 milliseconds", "25 milliseconds", "100 milliseconds"], answer: 2 },
      { q: "Where on an iPhone can you set a headphone volume limit?", options: ["Settings > Accessibility > Audio/Visual", "Settings > Sounds & Haptics > Headphone Safety", "Settings > Privacy > Microphone", "Settings > General > Hearing"], answer: 1 },
      { q: "What does 0 dBV equal?", options: ["0.775 volts", "1 volt", "1.23 volts", "1 milliwatt"], answer: 1 },
      { q: "What does 0 dBu equal?", options: ["1 volt", "1.23 volts", "0.775 volts", "0.316 volts"], answer: 2 },
      { q: "The professional standard operating level of +4 dBu equals approximately:", options: ["0.775 volts", "1 volt", "1.23 volts", "4 volts"], answer: 2 },
      { q: "The true difference between professional (+4 dBu) and consumer (-10 dBV) levels is approximately:", options: ["14 dB", "10 dB", "12 dB", "6 dB"], answer: 2 },
      { q: "0 dB SPL is defined as:", options: ["The threshold of pain", "The level of a normal conversation", "0.00002 pascals — the threshold of human hearing", "The reference level for studio monitors"], answer: 2 },
      { q: "The Nyquist theorem states that the sample rate must be at least:", options: ["Equal to the highest frequency you want to capture", "Four times the highest frequency you want to capture", "At least twice the highest frequency you want to capture", "Ten times the highest frequency you want to capture"], answer: 2 },
      { q: "What is aliasing in digital audio?", options: ["A technique for reducing file size", "A phantom frequency created when a signal above the Nyquist limit is incorrectly sampled", "Distortion caused by low bit depth", "Noise introduced during digital-to-analog conversion"], answer: 1 },
      { q: "What is the purpose of the anti-aliasing filter in an A/D converter?", options: ["To reduce quantization noise", "To remove any frequencies above the Nyquist frequency before sampling", "To add dither to the signal", "To control the gain of the preamp"], answer: 1 },
      { q: "Each bit of depth provides approximately how many dB of dynamic range?", options: ["3 dB", "6 dB", "12 dB", "20 dB"], answer: 1 },
      { q: "What dynamic range does 24-bit audio provide?", options: ["96 dB", "120 dB", "144 dB", "192 dB"], answer: 2 },
      { q: "What is quantization error?", options: ["The delay between recording and playback in a digital system", "The difference between the actual signal amplitude and the rounded digital value assigned to it", "Distortion caused by sample rate mismatch", "The noise floor of the analog preamp"], answer: 1 },
      { q: "What is dither and why is it used?", options: ["A type of lossy compression that reduces file size", "Low-level random noise added to reduce harsh quantization distortion at very low signal levels", "A word clock reference signal used for synchronization", "A high-pass filter applied before analog-to-digital conversion"], answer: 1 },
      { q: "What is latency in a digital audio system?", options: ["The noise floor of the converter", "The delay introduced as audio passes through the digital system including conversion, buffer, and plugins", "The frequency ceiling of the sample rate", "The difference between peak and RMS levels"], answer: 1 },
      { q: "Which audio format is the industry standard for professional audio production?", options: ["MP3 at 320 kbps", "AAC at 256 kbps", "WAV uncompressed PCM", "FLAC lossless compressed"], answer: 2 },
      { q: "What is the difference between lossless and lossy audio compression?", options: ["Lossless reduces file size by removing data permanently; lossy can be perfectly reconstructed", "Lossless can be perfectly reconstructed; lossy permanently removes audio data to reduce file size", "They are the same — both reduce file size without quality loss", "Lossless is only for video; lossy is for audio"], answer: 1 },
      { q: "Buffer size in a DAW controls:", options: ["The maximum number of tracks in a session", "The trade-off between latency and CPU stability — smaller buffer means lower latency but more CPU load", "The sample rate of the recording", "The bit depth of recorded audio"], answer: 1 },
      { q: "What is the correct sample rate and bit depth for most professional recording sessions today?", options: ["16-bit / 44.1 kHz", "24-bit / 44.1 kHz or 48 kHz", "32-bit / 96 kHz", "16-bit / 48 kHz"], answer: 1 },
      { q: "What is the difference between asynchronous and synchronous remote collaboration?", options: ["Asynchronous uses Dante; synchronous uses MADI", "Asynchronous means working at different times; synchronous means working simultaneously in real time", "Asynchronous is higher quality; synchronous introduces latency", "Asynchronous requires Pro Tools; synchronous works in any DAW"], answer: 1 },
      { q: "When exporting stems for a collaborator, all audio files should start at:", options: ["The first audio event in the session", "Bar 1 Beat 1 — even if the part does not come in until later", "The beginning of the first chorus", "Wherever the session markers begin"], answer: 1 },
      { q: "What is the industry standard professional tool for remote recording with sample-accurate sync?", options: ["Zoom", "Sonobus", "Source Connect", "Avid Control"], answer: 2 },
      { q: "In the Aux I/O Pro Tools to Zoom routing, which Audio Bridge path sends your mix TO Zoom?", options: ["Pro Tools Audio Bridge 2A", "Pro Tools Audio Bridge 2B", "Pro Tools Audio Bridge 16", "Pro Tools Audio Bridge 32"], answer: 1 },
      { q: "COPY vs ADD when importing audio into Pro Tools — what is the critical difference?", options: ["COPY is higher quality; ADD introduces sample rate conversion", "COPY writes the audio into the session's Audio Files folder keeping it self-contained; ADD just references the original location which can break the session", "ADD creates a duplicate file; COPY creates a reference", "They are identical — both create a copy in the Audio Files folder"], answer: 1 },
      { q: "What is the second harmonic of a 100Hz tone?", options: ["50 Hz", "150 Hz", "200 Hz", "300 Hz"], answer: 2 },
      { q: "What is the third harmonic of a 100Hz tone?", options: ["150 Hz", "200 Hz", "300 Hz", "400 Hz"], answer: 2 },
      { q: "Which waveform most closely resembles the sound of a bowed violin string?", options: ["Sine wave", "Square wave", "Triangle wave", "Sawtooth wave"], answer: 3 },
      { q: "What does increasing the number of sine waves in additive synthesis do to the resulting waveform?", options: ["Makes it quieter", "Makes it closer to the target waveform shape", "Removes harmonics", "Reduces the fundamental frequency"], answer: 1 },
      { q: "Sound is fundamentally created by:", options: ["Electrical signals in a circuit", "Something vibrating and moving air molecules", "The movement of electrons through a speaker coil", "Digital samples played back at high speed"], answer: 1 },
      { q: "In a waveform graph, what does the Y axis represent?", options: ["Time", "Frequency", "Displacement of air molecules", "Decibel level"], answer: 2 },
    ]
  }
];
]
  }
  ,{
    id: "waveforms-synthesis-1",
    category: "sound-synthesis",
    title: "Waveforms, Harmonics & Synthesis",
    description: "Periodic waveforms, harmonics, additive and subtractive synthesis, and how sound works.",
    timePerQuestion: 0,
    questions: [
      { q: "What does a waveform graph show?", options: ["The frequency spectrum of a sound at one instant", "How an air molecule's displacement changes over time", "The amplitude of a signal in decibels", "The number of harmonics in a sound"], answer: 1 },
      { q: "What is amplitude in the context of a waveform?", options: ["The number of times the wave repeats per second", "The speed at which sound travels through air", "How much an air molecule is displaced from its resting position", "The phase offset between two waves"], answer: 2 },
      { q: "What happens to a waveform when amplitude is set to zero?", options: ["The frequency doubles", "The wave inverts", "The line flattens — complete silence", "The wave becomes a square wave"], answer: 2 },
      { q: "What is frequency in audio?", options: ["The maximum displacement of an air molecule", "How many times a waveform repeats per second", "The time it takes for one full oscillation at maximum amplitude", "The difference between the highest and lowest points of a wave"], answer: 1 },
      { q: "What unit is frequency measured in?", options: ["Decibels", "Pascals", "Hertz", "Watts"], answer: 2 },
      { q: "What is the approximate range of human hearing?", options: ["1 Hz to 10,000 Hz", "20 Hz to 20,000 Hz", "100 Hz to 15,000 Hz", "50 Hz to 25,000 Hz"], answer: 1 },
      { q: "What note does a 440 Hz sine wave correspond to?", options: ["C4", "A4", "E4", "G4"], answer: 1 },
      { q: "What is a periodic waveform?", options: ["A waveform that changes amplitude over time", "A waveform that can be repeated to produce a constant tone", "A waveform with no harmonics", "A waveform that only contains sine waves"], answer: 1 },
      { q: "Which waveform is considered the fundamental waveform with no harmonics?", options: ["Square wave", "Sawtooth wave", "Triangle wave", "Sine wave"], answer: 3 },
      { q: "Why is the sine wave called the fundamental waveform?", options: ["It is the loudest of all waveforms", "It has the most harmonics", "It is pure — when you play a 440Hz sine wave the only frequency you hear is 440Hz", "It is the easiest to generate electronically"], answer: 2 },
      { q: "What are harmonics?", options: ["Additional frequencies created by certain waveforms beyond the root frequency", "The phase relationship between two sine waves", "The resonant frequency of an acoustic space", "The overtones added by compression"], answer: 0 },
      { q: "Harmonics are always at what frequency relationship to the root?", options: ["Random multiples of the root frequency", "Exact multiples of the root frequency", "Fractions of the root frequency", "Frequencies one octave above the root"], answer: 1 },
      { q: "Which waveform has only odd harmonics that taper off quickly?", options: ["Sine wave", "Sawtooth wave", "Square wave", "Triangle wave"], answer: 3 },
      { q: "Which waveform has only odd harmonics that do NOT taper off quickly, making it sound brighter?", options: ["Triangle wave", "Sine wave", "Square wave", "Sawtooth wave"], answer: 2 },
      { q: "Which waveform contains harmonics at every multiple of the root frequency — both odd and even?", options: ["Sine wave", "Triangle wave", "Square wave", "Sawtooth wave"], answer: 3 },
      { q: "How does increasing frequency affect the perceived pitch of a sound?", options: ["The pitch gets lower", "The pitch stays the same but gets louder", "The pitch gets higher", "The timbre changes but pitch stays the same"], answer: 2 },
      { q: "What is white noise?", options: ["A sine wave at very high frequency", "A square wave with maximum amplitude", "A uniform distribution of all audible frequencies with no discernible pitch", "A sawtooth wave with no harmonics"], answer: 2 },
      { q: "What does additive synthesis do?", options: ["Removes unwanted frequencies from a rich waveform using filters", "Builds complex sounds by layering multiple sine waves together", "Combines two audio signals to cancel phase", "Converts analog signals to digital using waveform addition"], answer: 1 },
      { q: "What does subtractive synthesis do?", options: ["Adds harmonics to a sine wave to create complexity", "Starts with a harmonically rich waveform and uses filters to remove frequencies", "Combines multiple sine waves to approximate a square wave", "Removes the fundamental frequency leaving only harmonics"], answer: 1 },
      { q: "Which type of synthesizer typically uses subtractive synthesis?", options: ["Organ", "Additive digital synthesizer", "Classic analog synthesizer like a Moog", "Sampler"], answer: 2 },
      { q: "Which instrument is a classic example of additive synthesis?", options: ["Moog synthesizer", "Electric guitar", "Organ", "Drum machine"], answer: 2 },
      { q: "What is waveform addition?", options: ["Increasing the amplitude of a waveform over time", "Combining two or more waveforms by adding their displacement values at each point", "Adding reverb to a dry signal", "Converting a waveform from mono to stereo"], answer: 1 },
      { q: "What is phase in the context of waveforms?", options: ["The maximum amplitude of a waveform", "The number of harmonics in a waveform", "The amount of time offset applied to a wave measured in degrees", "The frequency difference between two waves"], answer: 2 },
      { q: "What happens when two identical waves are 180 degrees out of phase and combined?", options: ["The sound doubles in amplitude", "The waves cancel each other out resulting in silence", "The frequency doubles", "The waveform becomes a square wave"], answer: 1 },
      { q: "How do noise-cancelling headphones work?", options: ["They boost frequencies the ear is less sensitive to", "They record ambient noise, offset its phase by 180 degrees, and mix it in to cancel the noise", "They use subtractive synthesis to filter background frequencies", "They use additive synthesis to mask unwanted sounds"], answer: 1 },
      { q: "What does the Fourier transform do?", options: ["Converts analog audio to digital", "Splits a complex wave into its individual sine wave components", "Adds harmonics to a sine wave", "Measures the amplitude of a waveform over time"], answer: 1 },
      { q: "What does a sawtooth waveform sound like compared to a sine wave?", options: ["Identical — they have the same harmonic content", "Much brighter and richer because it contains both odd and even harmonics", "Darker and rounder because it has fewer harmonics", "Quieter because its amplitude tapers off"], answer: 1 },
      { q: "Why does a square wave sound brighter than a triangle wave?", options: ["It has a higher fundamental frequency", "It has more amplitude", "It has the same odd harmonics but they don't taper off as quickly", "It contains even harmonics that the triangle wave doesn't"], answer: 2 },
      { q: "What file format uses Fourier transforms to compress audio by discarding less important frequencies?", options: ["WAV", "AIFF", "FLAC", "MP3"], answer: 3 },
      { q: "What image format uses a similar frequency-based compression technique to MP3?", options: ["PNG", "TIFF", "JPEG", "BMP"], answer: 2 },
      { q: "In subtractive synthesis, what tool is used to remove unwanted frequencies?", options: ["An oscillator", "A filter", "A compressor", "An envelope"], answer: 1 },
      { q: "What is the relationship between a waveform's frequency and its pitch?", options: ["Higher frequency means lower pitch", "Frequency and pitch are unrelated", "Higher frequency means higher pitch", "Pitch is determined by amplitude not frequency"], answer: 2 },
      { q: "According to additive synthesis theory, what waveform can theoretically be built from an infinite number of sine waves?", options: ["Triangle wave only", "Any periodic waveform including square and sawtooth", "Only waveforms with odd harmonics", "Only waveforms with even harmonics"], answer: 1 },
      { q: "What happens to a sound when you remove higher frequencies in subtractive synthesis?", options: ["It gets louder", "It sounds brighter", "It sounds darker and lower", "The pitch rises"], answer: 2 },
      { q: "What is the second harmonic of a 100Hz tone?", options: ["50 Hz", "150 Hz", "200 Hz", "300 Hz"], answer: 2 },
      { q: "What is the third harmonic of a 100Hz tone?", options: ["150 Hz", "200 Hz", "300 Hz", "400 Hz"], answer: 2 },
      { q: "Which waveform most closely resembles the sound of a bowed violin string?", options: ["Sine wave", "Square wave", "Triangle wave", "Sawtooth wave"], answer: 3 },
      { q: "What does increasing the number of sine waves in additive synthesis do to the resulting waveform?", options: ["Makes it quieter", "Makes it closer to the target waveform shape", "Removes harmonics", "Reduces the fundamental frequency"], answer: 1 },
      { q: "Sound is fundamentally created by:", options: ["Electrical signals in a circuit", "Something vibrating and moving air molecules", "The movement of electrons through a speaker coil", "Digital samples played back at high speed"], answer: 1 },
      { q: "In a waveform graph, what does the Y axis represent?", options: ["Time", "Frequency", "Displacement of air molecules", "Decibel level"], answer: 2 },
    ]
  }
];
