const CATEGORIES = [
  { id: "pro-tools", name: "Pro Tools", icon: "🎚", color: "#7C3AED" },
  { id: "ir-209", name: "IR-209", icon: "🎓", color: "#059669" },
];

const QUIZZES = [
  {
    id: "pt-shortcuts-1",
    category: "pro-tools",
    title: "Pro Tools Keyboard Shortcuts",
    description: "Test your knowledge of essential Pro Tools keyboard shortcuts for Mac.",
    timePerQuestion: 0,
    questions: [
      { q: "What is the shortcut to create an automation breakpoint?", options: ["Command + Click (in Automation Lane)", "Option + Click", "Control + Command + Click", "Command + Shift + Click"], answer: 0 },
      { q: "What is the shortcut to delete an automation breakpoint?", options: ["Command + Click", "Option + Click", "Control + Click", "Shift + Click"], answer: 1 },
      { q: "What shortcut enables plugin parameter automation?", options: ["Control + Command + Click", "Control + Command + Option + Click", "Option + Shift + Click", "Command + Shift + Click"], answer: 1 },
      { q: "How do you use fine resolution while dragging in Pro Tools?", options: ["Hold Option while dragging", "Hold Shift while dragging", "Hold Command while dragging", "Hold Control while dragging"], answer: 2 },
      { q: "What shortcut displays plugin parameter automation?", options: ["Control + Command + Click", "Option + Command + Click", "Control + Option + Click", "Shift + Command + Click"], answer: 0 },
      { q: "What shortcut shows the Volume Automation Lane on all tracks?", options: ["Option + =", "Option + -", "Command + -", "Control + -"], answer: 1 },
      { q: "What shortcut shows the Volume Automation Lane on the selected track?", options: ["-", "+", "=", "Option + ="], answer: 2 },
      { q: "What shortcut thins selected automation?", options: ["Option + Command + T", "Command + Shift + T", "Control + Option + T", "Option + Shift + T"], answer: 0 },
      { q: "What shortcut clears unused clips?", options: ["Command + Shift + U", "Command + Shift + B", "Option + Shift + B", "Command + Option + B"], answer: 1 },
      { q: "What shortcut selects unused clips?", options: ["Command + Shift + B", "Command + Shift + U", "Option + Shift + U", "Command + Option + U"], answer: 1 },
      { q: "What shortcut shows/hides Audio Clips in the Clips List?", options: ["Command + Shift + 2 on Numpad", "Command + Shift + 1 on Numpad", "Option + Shift + 1", "Control + Shift + 1"], answer: 1 },
      { q: "What shortcut shows/hides MIDI Clips in the Clips List?", options: ["Command + Shift + 1 on Numpad", "Command + Shift + 2 on Numpad", "Option + Shift + 2", "Control + Shift + 2"], answer: 1 },
      { q: "What shortcut creates a new session?", options: ["Command + Shift + N", "Command + N", "Command + Shift + O", "Control + N"], answer: 1 },
      { q: "What shortcut opens a recent session?", options: ["Command + O", "Command + Shift + N", "Command + Shift + O", "Option + O"], answer: 2 },
      { q: "What shortcut bounces the mix?", options: ["Command + B", "Option + Command + B", "Option + Shift + B", "Control + B"], answer: 1 },
      { q: "What shortcut bypasses all plugins on selected tracks?", options: ["Shift + Q", "Shift + A", "Shift + B", "Command + Shift + A"], answer: 1 },
      { q: "What shortcut bypasses all sends on selected tracks?", options: ["Shift + A", "Shift + S", "Shift + Q", "Command + Shift + Q"], answer: 2 },
      { q: "What shortcut closes all floating windows?", options: ["Control + Option + Command + W", "Command + Shift + W", "Option + Command + W", "Control + Command + W"], answer: 0 },
      { q: "What shortcut closes the current session?", options: ["Command + W", "Command + Shift + W", "Control + W", "Option + W"], answer: 1 },
      { q: "What shortcut consolidates clips?", options: ["Option + Shift + 2", "Option + Shift + 3", "Command + Shift + 3", "Control + Shift + 3"], answer: 1 },
      { q: "What shortcut creates fades?", options: ["Command + Shift + F", "Option + F", "Command + F", "Control + F"], answer: 2 },
      { q: "What shortcut duplicates a clip?", options: ["Command + C", "Command + V", "Command + D", "Command + Shift + D"], answer: 2 },
      { q: "What shortcut extends the selection to the beginning?", options: ["Shift + Option + Return", "Shift + Return", "Command + Return", "Option + Return"], answer: 1 },
      { q: "What shortcut extends the selection to the end?", options: ["Shift + Return", "Shift + Option + Return", "Command + Option + Return", "Control + Return"], answer: 1 },
      { q: "What shortcut fades in from start to cursor?", options: ["F", "G", "D", "A"], answer: 2 },
      { q: "What shortcut fades out from cursor to end?", options: ["D", "F", "A", "G"], answer: 3 },
      { q: "What shortcut executes fades using last settings?", options: ["D", "G", "F", "A"], answer: 2 },
      { q: "What shortcut groups clips?", options: ["Option + Command + U", "Option + Command + G", "Command + Shift + G", "Control + G"], answer: 1 },
      { q: "What shortcut imports audio?", options: ["Command + Shift + I", "Command + I", "Option + Shift + I", "Control + I"], answer: 0 },
      { q: "What shortcut imports session data?", options: ["Command + Shift + I", "Option + Shift + I", "Control + Shift + I", "Command + Option + I"], answer: 1 },
      { q: "What shortcut mutes a clip?", options: ["Command + Shift + M", "Option + M", "Command + M", "Control + M"], answer: 2 },
      { q: "What shortcut separates a clip at the selection?", options: ["S", "A", "B", "D"], answer: 2 },
      { q: "What shortcut snaps the clip start to the insertion point?", options: ["Control + Command + Click", "Control + Click", "Option + Click", "Command + Click"], answer: 1 },
      { q: "What shortcut snaps the clip end to the insertion point?", options: ["Control + Click", "Option + Command + Click", "Control + Command + Click", "Shift + Click"], answer: 2 },
      { q: "What shortcut suspends or un-suspends groups?", options: ["Command + Shift + U", "Command + Shift + G", "Option + G", "Control + G"], answer: 1 },
      { q: "What shortcut switches between the Edit and Mixer window?", options: ["Command + Shift + Equal", "Command + Equal", "Option + Equal", "Control + Equal"], answer: 1 },
      { q: "What shortcut trims the clip end to the cursor?", options: ["A", "T", "S", "D"], answer: 2 },
      { q: "What shortcut trims the clip start to the cursor?", options: ["S", "A", "D", "B"], answer: 1 },
      { q: "What shortcut trims a clip to the selection?", options: ["Command + Shift + T", "Option + T", "Command + T", "Control + T"], answer: 2 },
      { q: "What shortcut turns on the Smart Tool?", options: ["Command + 5", "Command + 6", "Command + 7", "Command + 8"], answer: 2 },
      { q: "What shortcut turns on/off Tab to Transient?", options: ["Command + Tab", "Option + Tab", "Command + Option + Tab", "Control + Tab"], answer: 2 },
      { q: "What shortcut turns on Keyboard Focus?", options: ["Option + Command + 2", "Option + Command + 1", "Command + Shift + 1", "Control + Option + 1"], answer: 1 },
      { q: "What shortcut ungroups clips?", options: ["Option + Command + G", "Option + Command + U", "Command + Shift + U", "Control + U"], answer: 1 },
      { q: "What shortcut turns on/off the click track?", options: ["7 on Numpad", "8 on Numpad", "9 on Numpad", "6 on Numpad"], answer: 1 },
      { q: "What shortcut turns on/off the metronome?", options: ["8 on Numpad", "7 on Numpad", "6 on Numpad", "9 on Numpad"], answer: 1 },
      { q: "What shortcut turns on/off the count off?", options: ["8 on Numpad", "6 on Numpad", "7 on Numpad", "9 on Numpad"], answer: 2 },
      { q: "What shortcut nudges a clip by the selected amount?", options: ["Left or Right Arrow", "Plus or Minus on Numpad", "Command + Left or Right Arrow", "Option + Left or Right Arrow"], answer: 1 },
      { q: "What shortcut opens the Keyboard Commands window?", options: ["Control + Shift + W", "Control + Shift + K", "Command + Shift + K", "Option + Shift + K"], answer: 1 },
      { q: "What shortcut clears clip indicators?", options: ["Option + I", "Command + C", "Option + C", "Control + C"], answer: 2 },
      { q: "What shortcut turns on/off Link Track and Edit Selection?", options: ["Command + T", "Option + T", "Shift + T", "Control + T"], answer: 2 },
      { q: "What shortcut turns all MIDI notes off?", options: ["Shift + Command + .", "Command + Option + .", "Control + Shift + .", "Option + Shift + ."], answer: 0 },
      { q: "What shortcut opens the MIDI Editor?", options: ["Control + Option + Equal", "Control + Equal", "Command + Equal", "Option + Equal"], answer: 1 },
      { q: "What shortcut opens the MIDI Typing Keyboard?", options: ["Control + K", "Command + K", "Shift + K", "Option + K"], answer: 2 },
      { q: "What shortcut increases or decreases MIDI velocity by 5?", options: ["Shift + Up or Down Arrow", "Command + Shift + Up or Down Arrow", "Command + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 2 },
      { q: "What shortcut increases or decreases MIDI velocity by 15?", options: ["Command + Up or Down Arrow", "Command + Shift + Up or Down Arrow", "Shift + Up or Down Arrow", "Option + Shift + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut transposes MIDI up or down an octave?", options: ["Command + Up or Down Arrow", "Option + Up or Down Arrow", "Shift + Up or Down Arrow", "Control + Up or Down Arrow"], answer: 2 },
      { q: "What shortcut shows/hides the MIDI Event List?", options: ["Option + Equal", "Control + Equal", "Command + Equal", "Shift + Equal"], answer: 0 },
      { q: "What shortcut trims MIDI end by grid value?", options: ["Control + Left or Right Arrow", "Option + Left or Right Arrow", "Command + Left or Right Arrow", "Shift + Left or Right Arrow"], answer: 1 },
      { q: "What shortcut trims MIDI start by grid value?", options: ["Option + Left or Right Arrow", "Command + Left or Right Arrow", "Control + Left or Right Arrow", "Shift + Left or Right Arrow"], answer: 2 },
      { q: "What shortcut creates a new track?", options: ["Command + N", "Command + T", "Command + Shift + N", "Control + Shift + N"], answer: 2 },
      { q: "What shortcut changes from mono to stereo in the New Track window?", options: ["Command + Up or Down Arrow", "Command + Shift + Left or Right Arrow", "Command + Left or Right Arrow", "Option + Left or Right Arrow"], answer: 2 },
      { q: "What shortcut changes the track type in the New Track window?", options: ["Command + Left or Right Arrow", "Command + Up or Down Arrow", "Shift + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut zooms in and out horizontally in Pro Tools?", options: ["Command + [ or ]", "Option + [ or ]", "R and T", "Z and X"], answer: 2 },
      { q: "What shortcut changes all track heights in the session?", options: ["Control + Up or Down Arrow", "Control + Option + Up or Down Arrow", "Command + Option + Up or Down Arrow", "Shift + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut changes the selected track height?", options: ["Control + Option + Up or Down Arrow", "Control + Up or Down Arrow", "Command + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 1 },
      { q: "What shortcut zooms in on a selection horizontally?", options: ["Control + Command + [", "Control + Command + ]", "Option + Command + ]", "Command + Shift + ]"], answer: 1 },
      { q: "What shortcut zooms to show all horizontally and preserves waveform zoom?", options: ["Option + A", "Control + Command + ]", "Control + Command + [", "Command + Shift + ["], answer: 2 },
      { q: "What shortcut zooms to show all horizontally and resets waveform zoom?", options: ["Control + Command + [", "Control + Command + ]", "Option + A", "Command + Option + A"], answer: 2 },
      { q: "What shortcut zooms in and out audio waveforms?", options: ["R and T", "Command + [ or ]", "Command + Option + [ or ]", "Control + [ or ]"], answer: 2 },
      { q: "What shortcut fits all track sizes to the window?", options: ["Control + Option + Up or Down Arrow", "Control + Option + Command + Down Arrow", "Control + Command + Down Arrow", "Option + Command + Down Arrow"], answer: 1 },
      { q: "What shortcut cycles through playlists on selected tracks?", options: ["Command + Up or Down Arrow", "Control + Up or Down Arrow", "Shift + Up or Down Arrow", "Option + Up or Down Arrow"], answer: 2 },
      { q: "What shortcut cycles through playlists within a selection?", options: ["Shift + Up or Down Arrow", "Shift + Command + Up or Down Arrow", "Control + Shift + Up or Down Arrow", "Option + Shift + Up or Down Arrow"], answer: 1 },
    ]
  }
];
